<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIhlLkZq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIhlLkZq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIhlLkZq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIhlLkZq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIhlLkZq\App_KernelDevDebugContainer([
    'container.build_hash' => 'IhlLkZq',
    'container.build_id' => '5d51e490',
    'container.build_time' => 1721725095,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIhlLkZq');
